add flash-uart to makefile

diff --git a/firmware/PowerDistributionUnit_Mk1/Makefile b/firmware/PowerDistributionUnit_Mk1/Makefile
--- a/firmware/PowerDistributionUnit_Mk1/Makefile
+++ b/firmware/PowerDistributionUnit_Mk1/Makefile
@@ -142,6 +142,15 @@ flash:
 	fi
 # -----------------------------------------------------------------------------
 
+# FLASH-UART ------------------------------------------------------------------
+flash-uart:
+	@set -o pipefail; if $(MAKE) -C $(BUILD_MAKEFILE_DIR) flash-uart; then \
+		echo -e "${GREEN}Flash successful.\n${NC}"; \
+	else \
+		echo -e "${RED}Flash failure.\n${NC}"; \
+		exit 1; \
+	fi
+# -----------------------------------------------------------------------------
 
 # CLEAN -----------------------------------------------------------------------
 clean:
